title: Dhiraj Gupta # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Software Engineer
  <br><br>
  <a href="mailto:dhirajkrshah@gmail.com">dhirajkrshah@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/dhiraj-kumar-gupta-390ab281/">LinkedIn Profile</a>
  <br>
theme: jekyll-theme-minimal
